controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

checkout_create:
    path: /create-checkout-session/{id}
    controller: App\Controller\PaymentController::createCheckoutSession
